version: '3.1'

services:
  app:
    image: ${IMAGE}:${VERSION}
    env_file:
      - .env
    environment:
      DATABASE_ENDPOINT: database
    depends_on:
      - database
    ports:
      - 8080:8080
      - 8081:8081
